"""Added the relationships

Revision ID: 1bf4eb304712
Revises: 8edcdbc22a4b
Create Date: 2022-12-13 12:53:12.260730

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1bf4eb304712'
down_revision = '8edcdbc22a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bms_servers', sa.Column('db_tool_id', sa.Integer(), nullable=True))
    op.add_column('bms_servers', sa.Column('db_version', sa.String(), nullable=True))
    op.add_column('bms_servers', sa.Column('db_port', sa.Numeric(), nullable=True))
    op.create_foreign_key(None, 'bms_servers', 'dbtools', ['db_tool_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bms_servers', type_='foreignkey')
    op.drop_column('bms_servers', 'db_port')
    op.drop_column('bms_servers', 'db_version')
    op.drop_column('bms_servers', 'db_tool_id')
    # ### end Alembic commands ###
