# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""extend RestoreConfig

Revision ID: 32b82c34703c
Revises: ec4b37b1b822
Create Date: 2022-05-23 13:44:07.815516

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '32b82c34703c'
down_revision = 'ec4b37b1b822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restore_configs', sa.Column('run_pre_restore', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('restore_configs', sa.Column('validations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restore_configs', 'validations')
    op.drop_column('restore_configs', 'run_pre_restore')
    # ### end Alembic commands ###
