# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""add Operation.Sub_type

Revision ID: 32c827858686
Revises: d06c49d2ce88
Create Date: 2022-04-05 14:47:33.475360

"""
from enum import Enum
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '32c827858686'
down_revision = 'd06c49d2ce88'
branch_labels = None
depends_on = None


class OperationSubType(Enum):
    FULL = 'FULL'
    INCREMENTAL = 'INCREMENTAL'
    ARCHIVE_LOG = 'ARCHIVE_LOG'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation_details', sa.Column('sub_type', sqlalchemy_utils.types.choice.ChoiceType(OperationSubType, impl=sa.String(20)), nullable=True))
    op.alter_column('operation_details', 'wave_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation_details', 'wave_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('operation_details', 'sub_type')
    # ### end Alembic commands ###
