# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""add RestoreConfig.control_file

Revision ID: 3bdf560f8b00
Revises: c1cd9d50ef79
Create Date: 2022-04-14 10:03:16.891803

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '3bdf560f8b00'
down_revision = 'c1cd9d50ef79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restore_configs', sa.Column('control_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restore_configs', 'control_file')
    # ### end Alembic commands ###
