# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""add SourceDB.oracle_release

Revision ID: 521f9d112afc
Revises: 46b528bd81dc
Create Date: 2022-01-05 19:22:23.186464

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '521f9d112afc'
down_revision = '46b528bd81dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_dbs', sa.Column('oracle_release', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_dbs', 'oracle_release')
    # ### end Alembic commands ###
