"""Addeding Not Null Constraints to Existing BMS columns

Revision ID: 5969aa58046d
Revises: 1bf4eb304712
Create Date: 2022-12-13 13:00:10.950773

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '5969aa58046d'
down_revision = '1bf4eb304712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_dbs', 'oracle_version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('source_dbs', 'arch',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_dbs', 'arch',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('source_dbs', 'oracle_version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
