# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""add project_id to SourceDB unique constraint

Revision ID: 7e66f5df8bb3
Revises: 67c3aa849e05
Create Date: 2022-02-07 14:46:43.439273

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7e66f5df8bb3'
down_revision = '67c3aa849e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('source_dbs_server_db_name_key', 'source_dbs', type_='unique')
    op.create_unique_constraint(None, 'source_dbs', ['server', 'db_name', 'project_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source_dbs', type_='unique')
    op.create_unique_constraint('source_dbs_server_db_name_key', 'source_dbs', ['server', 'db_name'])
    # ### end Alembic commands ###
