# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Remove service_account

Revision ID: 9097d83b015a
Revises: 84da00d955d1
Create Date: 2022-03-03 00:49:03.023541

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9097d83b015a'
down_revision = '84da00d955d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'service_account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('service_account', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
