"""update of changes for CloudSQL

Revision ID: 9278ac279ce9
Revises: 3b825ba0b5a6
Create Date: 2022-11-29 13:30:07.866123

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9278ac279ce9'
down_revision = '3b825ba0b5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbtools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbtools_type'), 'dbtools', ['type'], unique=False)
    op.add_column('configs', sa.Column('network_config_values', sa.JSON(), nullable=True))
    op.add_column('source_dbs', sa.Column('db_tool_id', sa.Integer(), nullable=True))
    op.add_column('source_dbs', sa.Column('db_version', sa.String(), nullable=True))
    op.add_column('source_dbs', sa.Column('db_port', sa.Numeric(), nullable=True))
    op.create_foreign_key(None, 'source_dbs', 'dbtools', ['db_tool_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source_dbs', type_='foreignkey')
    op.drop_column('source_dbs', 'db_port')
    op.drop_column('source_dbs', 'db_version')
    op.drop_column('source_dbs', 'db_tool_id')
    op.drop_column('configs', 'network_config_values')
    op.drop_index(op.f('ix_dbtools_type'), table_name='dbtools')
    op.drop_table('dbtools')
    # ### end Alembic commands ###