# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""add RestoreConfig.backup_type

Revision ID: 9b3a6b051b79
Revises: fd984d3f7fe2
Create Date: 2022-04-06 15:23:51.521344

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9b3a6b051b79'
down_revision = 'fd984d3f7fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restore_configs', sa.Column('backup_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restore_configs', 'backup_type')
    # ### end Alembic commands ###
