# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""move sub_type to Operation

Revision ID: c1cd9d50ef79
Revises: 9b3a6b051b79
Create Date: 2022-04-06 21:35:44.298825

"""
from enum import Enum
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c1cd9d50ef79'
down_revision = '9b3a6b051b79'
branch_labels = None
depends_on = None


class OperationSubType(Enum):
    FULL = 'FULL'
    INCREMENTAL = 'INCREMENTAL'
    ARCHIVE_LOG = 'ARCHIVE_LOG'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation_details', 'sub_type')
    op.add_column('operations', sa.Column('sub_type', sqlalchemy_utils.types.choice.ChoiceType(OperationSubType, impl=sa.String(20)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operations', 'sub_type')
    op.add_column('operation_details', sa.Column('sub_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
