# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""switch to config.is_configured

Revision ID: d06c49d2ce88
Revises: 9a0c342204b9
Create Date: 2022-03-08 20:15:04.146146

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'd06c49d2ce88'
down_revision = '9a0c342204b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configs', sa.Column('is_configured', sa.Boolean(), nullable=True))
    op.execute('UPDATE configs set is_configured = FALSE')
    op.drop_column('configs', 'draft')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configs', sa.Column('draft', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('configs', 'is_configured')
    # ### end Alembic commands ###
