# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""change ScheduledTask.schedule_time

Revision ID: e5a4a7e5afba
Revises: a843bbcc5b82
Create Date: 2022-04-22 11:31:57.307055

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5a4a7e5afba'
down_revision = 'a843bbcc5b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_tasks', sa.Column('schedule_time', sa.DateTime(), nullable=False))
    op.drop_column('scheduled_tasks', 'scheduled_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_tasks', sa.Column('scheduled_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('scheduled_tasks', 'schedule_time')
    # ### end Alembic commands ###
