# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""change Label.name length

Revision ID: e793e0ed1570
Revises: f5a766699862
Create Date: 2022-04-28 16:32:43.681527

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'e793e0ed1570'
down_revision = 'f5a766699862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('labels', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=15),
               existing_nullable=False,
               existing_server_default=sa.text(u"''::character varying"))    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('labels', 'name',
               existing_type=sa.VARCHAR(15),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text(u"''::character varying"))    # ### end Alembic commands ###
    # ### end Alembic commands ###
