# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""empty message

Revision ID: ea47877dbe58
Revises: 3bdf560f8b00
Create Date: 2022-04-19 18:56:35.453292

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'ea47877dbe58'
down_revision = '3bdf560f8b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restore_configs', 'is_configured',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('restore_configs', 'pfile_file',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('restore_configs', 'pwd_file',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('restore_configs', 'tnsnames_file',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('restore_configs', 'listener_file',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('restore_configs', 'control_file',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restore_configs', 'control_file',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('restore_configs', 'listener_file',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('restore_configs', 'tnsnames_file',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('restore_configs', 'pwd_file',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('restore_configs', 'pfile_file',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('restore_configs', 'is_configured',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
