# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Add OperationDetailsError

Revision ID: ec4b37b1b822
Revises: e793e0ed1570
Create Date: 2022-05-10 12:17:37.557777

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'ec4b37b1b822'
down_revision = 'e793e0ed1570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_details_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_details_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['operation_details_id'], ['operation_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_details_errors')
    # ### end Alembic commands ###
