# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""add Labels constraints

Revision ID: f5a766699862
Revises: d4ae09a4225f
Create Date: 2022-04-28 16:20:11.581237

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'f5a766699862'
down_revision = 'd4ae09a4225f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_labels_name'), 'labels', ['name'], unique=False)
    op.create_unique_constraint(None, 'labels', ['name', 'project_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labels', type_='unique')
    op.drop_index(op.f('ix_labels_name'), table_name='labels')
    # ### end Alembic commands ###
